### PR TITLE
Final Edit

### PR DESCRIPTION
**Pull request by josiasrico**
Updated css to add color.

### CODE REVIEW

**Comment by josiasrico** [comment]
Hi @geravm . This is my site for you to review

**Comment by Rantelo** [comment]
Hey men, your site looks awesome.
Take a look at your table in the README.md
It is not rendering well once you transform it. Look for the tables format for mkdocs, to see if there is something you are missing

**Comment by LibertadPantoja-Wize** [comment]
Looking good! I think that the problem with your dog's table can be solved by adding a break before the table (that helped me with one of my files). 
Another break may help to fix the first ennumeration deployment as well.
In the Experience section, I would change Professor to Teacher, because Professor is usually used for faculty memebers. 
Also in selected past work, maybe the freelance experiences and UX Research for a data-processing platform could be changed to full title case.

**Comment by josiasrico** [comment]
> Hey men, your site looks awesome.
> Take a look at your table in the README.md
> It is not rendering well once you transform it. Look for the tables format for mkdocs, to see if there is something you are missing

Thanks for the comments. I modified the README.md but it wont change. I noticed that the index.html document is the one rendering that table that shouldnt be even there.

**Comment by josiasrico** [comment]
> Looking good! I think that the problem with your dog's table can be solved by adding a break before the table (that helped me with one of my files).
> Another break may help to fix the first ennumeration deployment as well.
> In the Experience section, I would change Professor to Teacher, because Professor is usually used for faculty memebers.
> Also in selected past work, maybe the freelance experiences and UX Research for a data-processing platform could be changed to full title case.


Thanks for the comments. Will change

**Comment by josiasrico** [comment]
Merge

**Pull request merged**
